const { app, BrowserWindow, ipcMain, Tray, Menu, dialog, nativeImage } = require('electron');
const { autoUpdater } = require('electron-updater');
const path = require('path');
const fs = require('fs');
const crypto = require('crypto');

const VERSION = '1.2.1';
const UPDATE_INFO = [
  { version: '1.2.1', date: '2026-04-16', changes: ['Исправлена миграция БД для topic_ids', 'Автоматическое добавление колонок'] },
  { version: '1.2.0', date: '2026-04-15', changes: ['Экспорт/импорт', 'Topics', 'Веб-режим'] },
  { version: '1.1.0', date: '2026-04-15', changes: ['Очистка сообщений', 'Редактирование', 'Логи'] }
];

let win, tray, pollingIntervals = {}, botOffsets = {}, db, scheduleIntervals = [];

const ENCRYPTION_KEY = crypto.scryptSync(app.getPath('userData'), 'hubpro-salt', 32);
const IV_LENGTH = 16;

function encrypt(text) { if (!text) return text; const iv = crypto.randomBytes(IV_LENGTH); const cipher = crypto.createCipheriv('aes-256-cbc', ENCRYPTION_KEY, iv); let encrypted = cipher.update(text, 'utf8', 'hex'); encrypted += cipher.final('hex'); return iv.toString('hex') + ':' + encrypted; }
function decrypt(text) { if (!text || !text.includes(':')) return text; try { const parts = text.split(':'); const iv = Buffer.from(parts[0], 'hex'); const decipher = crypto.createDecipheriv('aes-256-cbc', ENCRYPTION_KEY, iv); let decrypted = decipher.update(parts[1], 'hex', 'utf8'); decrypted += decipher.final('utf8'); return decrypted; } catch (e) { return text; } }
function hashPassword(password) { return crypto.createHash('sha256').update(password).digest('hex'); }

function initDatabase() {
  const Database = require('better-sqlite3');
  const dbPath = path.join(app.getPath('userData'), 'hubpro.db');
  db = new Database(dbPath);
  
  // Создаём таблицы
  db.exec(`CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, login TEXT UNIQUE, password TEXT, role TEXT DEFAULT 'user', created_at DATETIME DEFAULT CURRENT_TIMESTAMP, delete_request INTEGER DEFAULT 0);
    CREATE TABLE IF NOT EXISTS bots (id INTEGER PRIMARY KEY, name TEXT, token TEXT UNIQUE, online INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS groups (id INTEGER PRIMARY KEY, name TEXT, chat_id TEXT, bot_id INTEGER, topic_ids TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(bot_id) REFERENCES bots(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS messages (id INTEGER PRIMARY KEY, group_id INTEGER, text TEXT, sent INTEGER DEFAULT 1, sender TEXT, time DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS schedules (id INTEGER PRIMARY KEY, name TEXT, text TEXT, group_id INTEGER, bot_id INTEGER, scheduled_time TEXT, repeat_type TEXT DEFAULT 'once', status TEXT DEFAULT 'pending', last_executed DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY(group_id) REFERENCES groups(id) ON DELETE CASCADE, FOREIGN KEY(bot_id) REFERENCES bots(id) ON DELETE CASCADE);
    CREATE TABLE IF NOT EXISTS schedule_logs (id INTEGER PRIMARY KEY, schedule_id INTEGER, status TEXT, error TEXT, executed_at DATETIME DEFAULT CURRENT_TIMESTAMP);
    CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT);`);
  
  // Миграция: добавляем колонку topic_ids если её нет
  try { db.exec(`ALTER TABLE groups ADD COLUMN topic_ids TEXT`); } catch (e) { /* уже есть */ }
  
  if (!db.prepare('SELECT id FROM users WHERE login = ?').get('NeuralAP')) {
    db.prepare('INSERT INTO users (login, password, role) VALUES (?, ?, ?)').run('NeuralAP', hashPassword('0901Admin'), 'admin');
  }
  console.log('Database:', dbPath);
  return db;
}

function registerIPCHandlers() {
  ipcMain.handle('app:getVersion', () => ({ version: VERSION, updates: UPDATE_INFO }));
  ipcMain.handle('data:export', async () => { try { return { success: true, data: { bots: db.prepare('SELECT id, name, token, online, created_at FROM bots').all().map(b => ({...b, token: decrypt(b.token)})), groups: db.prepare('SELECT g.id, g.name, g.chat_id, g.bot_id, g.topic_ids, g.created_at, b.name as bot_name FROM groups g LEFT JOIN bots b ON g.bot_id = b.id').all(), schedules: db.prepare('SELECT s.*, g.name as group_name, b.name as bot_name FROM schedules s LEFT JOIN groups g ON s.group_id = g.id LEFT JOIN bots b ON s.bot_id = b.id').all() } }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('data:import', async (_, { bots, groups, schedules }) => { try { if (bots) for (const b of bots) if (b.name && b.token) try { db.prepare('INSERT OR IGNORE INTO bots (name, token, online) VALUES (?, ?, ?)').run(b.name, encrypt(b.token), b.online ? 1 : 0); } catch(e) {} if (groups) for (const g of groups) if (g.name && g.chat_id && g.bot_id) try { db.prepare('INSERT OR IGNORE INTO groups (name, chat_id, bot_id, topic_ids) VALUES (?, ?, ?, ?)').run(g.name, g.chat_id, g.bot_id, g.topic_ids || null); } catch(e) {} if (schedules) for (const s of schedules) if (s.name && s.text && s.group_id && s.bot_id) try { db.prepare('INSERT OR IGNORE INTO schedules (name, text, group_id, bot_id, scheduled_time, repeat_type, status) VALUES (?, ?, ?, ?, ?, ?, ?)').run(s.name, s.text, s.group_id, s.bot_id, s.scheduled_time, s.repeat_type || 'once', s.status || 'active'); } catch(e) {} return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('auth:login', (_, { login, password }) => { const user = db.prepare('SELECT * FROM users WHERE login = ?').get(login); if (!user) return { success: false, error: 'Пользователь не найден' }; if (user.password !== hashPassword(password)) return { success: false, error: 'Неверный пароль' }; if (user.delete_request === 1) return { success: false, error: 'Аккаунт отмечен на удаление' }; return { success: true, user: { id: user.id, login: user.login, role: user.role } }; });
  ipcMain.handle('auth:getUsers', () => db.prepare('SELECT id, login, role, created_at, delete_request FROM users ORDER BY id').all());
  ipcMain.handle('auth:addUser', (_, { login, password, role }) => { try { if (db.prepare('SELECT id FROM users WHERE login = ?').get(login)) return { success: false, error: 'Логин занят' }; db.prepare('INSERT INTO users (login, password, role) VALUES (?, ?, ?)').run(login, hashPassword(password), role || 'user'); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('auth:updateUser', (_, { id, login, password, currentUserId, currentUserRole }) => { try { if (id !== currentUserId && currentUserRole !== 'admin') return { success: false, error: 'Нет прав' }; if (login) { if (db.prepare('SELECT id FROM users WHERE login = ? AND id != ?').get(login, id)) return { success: false, error: 'Логин занят' }; db.prepare('UPDATE users SET login = ? WHERE id = ?').run(login, id); } if (password) db.prepare('UPDATE users SET password = ? WHERE id = ?').run(hashPassword(password), id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('auth:requestDelete', (_, id) => { try { db.prepare('UPDATE users SET delete_request = 1 WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('auth:approveDelete', (_, id) => { try { db.prepare('DELETE FROM users WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('auth:cancelDelete', (_, id) => { try { db.prepare('UPDATE users SET delete_request = 0 WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:getBots', () => db.prepare('SELECT * FROM bots ORDER BY id').all().map(b => ({ ...b, token: decrypt(b.token) })));
  ipcMain.handle('db:addBot', (_, { name, token }) => { try { const result = db.prepare('INSERT INTO bots (name, token, online) VALUES (?, ?, 0)').run(name, encrypt(token)); return { success: true, id: result.lastInsertRowid }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:updateBot', (_, { id, name, token, online }) => { try { if (token) db.prepare('UPDATE bots SET name = ?, token = ?, online = ? WHERE id = ?').run(name, encrypt(token), online ? 1 : 0, id); else db.prepare('UPDATE bots SET name = ?, online = ? WHERE id = ?').run(name, online ? 1 : 0, id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:deleteBot', (_, id) => { try { db.prepare('DELETE FROM bots WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:getGroups', () => db.prepare('SELECT g.*, b.name as bot_name FROM groups g LEFT JOIN bots b ON g.bot_id = b.id ORDER BY g.id').all());
  ipcMain.handle('db:addGroup', (_, { name, chatId, botId, topicIds }) => { try { const result = db.prepare('INSERT INTO groups (name, chat_id, bot_id, topic_ids) VALUES (?, ?, ?, ?)').run(name, chatId, botId, topicIds || null); return { success: true, id: result.lastInsertRowid }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:updateGroup', (_, { id, name, chatId, botId, topicIds }) => { try { db.prepare('UPDATE groups SET name = ?, chat_id = ?, bot_id = ?, topic_ids = ? WHERE id = ?').run(name, chatId, botId, topicIds || null, id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:deleteGroup', (_, id) => { try { db.prepare('DELETE FROM groups WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:getMessages', (_, groupId) => db.prepare('SELECT * FROM messages WHERE group_id = ? ORDER BY time ASC').all(groupId));
  ipcMain.handle('db:addMessage', (_, { groupId, text, sent, sender }) => { try { const result = db.prepare('INSERT INTO messages (group_id, text, sent, sender) VALUES (?, ?, ?, ?)').run(groupId, text, sent ? 1 : 0, sender || null); return { success: true, id: result.lastInsertRowid }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:clearMessages', (_, groupId) => { try { if (groupId) db.prepare('DELETE FROM messages WHERE group_id = ?').run(groupId); else db.prepare('DELETE FROM messages').run(); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:getSchedules', () => db.prepare('SELECT s.*, g.name as group_name, g.chat_id, b.name as bot_name FROM schedules s LEFT JOIN groups g ON s.group_id = g.id LEFT JOIN bots b ON s.bot_id = b.id ORDER BY s.id').all());
  ipcMain.handle('db:getScheduleLogs', (_, scheduleId) => db.prepare('SELECT * FROM schedule_logs WHERE schedule_id = ? ORDER BY executed_at DESC LIMIT 50').all(scheduleId));
  ipcMain.handle('db:addSchedule', (_, { name, text, groupId, botId, scheduledTime, repeatType }) => { try { const result = db.prepare('INSERT INTO schedules (name, text, group_id, bot_id, scheduled_time, repeat_type, status) VALUES (?, ?, ?, ?, ?, ?, ?)').run(name, text, groupId, botId, scheduledTime, repeatType, 'active'); return { success: true, id: result.lastInsertRowid }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:updateSchedule', (_, { id, name, text, groupId, botId, scheduledTime, repeatType }) => { try { db.prepare('UPDATE schedules SET name = ?, text = ?, group_id = ?, bot_id = ?, scheduled_time = ?, repeat_type = ? WHERE id = ?').run(name, text, groupId, botId, scheduledTime, repeatType, id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:deleteSchedule', (_, id) => { try { db.prepare('DELETE FROM schedules WHERE id = ?').run(id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:toggleSchedule', (_, { id, status }) => { try { db.prepare('UPDATE schedules SET status = ? WHERE id = ?').run(status, id); return { success: true }; } catch (err) { return { success: false, error: err.message }; } });
  ipcMain.handle('db:getStats', () => ({ botCount: db.prepare('SELECT COUNT(*) as c FROM bots').get().c, groupCount: db.prepare('SELECT COUNT(*) as c FROM groups').get().c, messageCount: db.prepare('SELECT COUNT(*) as c FROM messages').get().c, scheduleCount: db.prepare('SELECT COUNT(*) as c FROM schedules').get().c, userCount: db.prepare('SELECT COUNT(*) as c FROM users').get().c, deleteRequests: db.prepare('SELECT COUNT(*) as c FROM users WHERE delete_request = 1').get().c }));
  ipcMain.on('tg:sync-config', async () => { const bots = db.prepare('SELECT * FROM bots WHERE online = 1').all(); const groups = db.prepare('SELECT * FROM groups').all(); syncPolling(bots, groups); });
  ipcMain.handle('tg:send', async (_, { token, chatId, text, topicIds }) => { try { const me = await (await fetch(`https://api.telegram.org/bot${token}/getMe`)).json(); if (!me.ok) return { ok: false, description: 'Неверный токен' }; const chat = await (await fetch(`https://api.telegram.org/bot${token}/getChat?chat_id=${chatId}`)).json(); if (!chat.ok) return { ok: false, description: 'Бот не в группе' }; if (topicIds && Array.isArray(topicIds) && topicIds.length > 0) { const results = []; for (const tid of topicIds) results.push(await (await fetch(`https://api.telegram.org/bot${token}/sendMessage`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ chat_id: chatId, text, message_thread_id: tid, parse_mode: 'HTML' }) })).json()); return { ok: results.every(r => r.ok), results }; } const res = await fetch(`https://api.telegram.org/bot${token}/sendMessage`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ chat_id: chatId, text, parse_mode: 'HTML' }) }); return await res.json(); } catch (err) { return { ok: false, description: err.message }; } });
  ipcMain.handle('tg:checkBot', async (_, token) => { try { return await (await fetch(`https://api.telegram.org/bot${token}/getMe`)).json(); } catch (err) { return { ok: false, error: err.message }; } });
  ipcMain.handle('tg:getTopics', async (_, { token, chatId }) => { try { const data = await (await fetch(`https://api.telegram.org/bot${token}/getForumTopics?chat_id=${chatId}`)).json(); return data.ok ? { ok: true, topics: data.topics || [] } : { ok: false, error: data.description }; } catch (err) { return { ok: false, error: err.message }; } });
  console.log('IPC handlers registered');
}

autoUpdater.autoDownload = true; autoUpdater.autoInstallOnAppQuit = true;
app.whenReady().then(async () => { db = initDatabase(); registerIPCHandlers(); createWindow(); await createTray(); setupAutoUpdater(); startScheduleChecker(); const bots = db.prepare('SELECT * FROM bots WHERE online = 1').all(); const groups = db.prepare('SELECT * FROM groups').all(); syncPolling(bots, groups); });

function createWindow() { win = new BrowserWindow({ width: 1280, height: 850, title: 'HubPro v' + VERSION, webPreferences: { preload: path.join(__dirname, 'preload.js'), contextIsolation: true, nodeIntegration: false }, show: false }); win.loadFile('renderer/index.html'); win.once('ready-to-show', () => win.show()); win.on('close', (e) => { if (!app.isQuitting) { e.preventDefault(); win.hide(); } }); }

async function createTray() {
  const buildDir = path.join(__dirname, 'build'); if (!fs.existsSync(buildDir)) fs.mkdirSync(buildDir, { recursive: true });
  const iconPath = path.join(buildDir, 'icon.png');
  if (!fs.existsSync(iconPath)) fs.writeFileSync(iconPath, Buffer.from([0x89,0x50,0x4E,0x47,0x0D,0x0A,0x1A,0x0A,0x00,0x00,0x00,0x0D,0x49,0x48,0x44,0x52,0x00,0x00,0x00,0x10,0x00,0x00,0x00,0x10,0x08,0x06,0x00,0x00,0x00,0x1F,0xF3,0xFF,0x61,0x00,0x00,0x00,0x01,0x73,0x52,0x47,0x42,0x00,0xAE,0xCE,0x1C,0xE9,0x00,0x00,0x00,0x3D,0x49,0x44,0x41,0x54,0x38,0x4F,0x63,0x64,0x60,0x18,0x05,0xA3,0x00,0x31,0x80,0x98,0x98,0x98,0x98,0x18,0x05,0xA3,0x00,0x31,0x80,0x98,0x98,0x98,0x98,0x18,0x05,0xA3,0x00,0x31,0x80,0x98,0x98,0x98,0x98,0x18,0x05,0xA3,0x00,0x31,0x80,0x98,0x98,0x98,0x98,0x18,0x05,0xA3,0x00,0x00,0x0A,0x3F,0x04,0x1C,0xB8,0xD1,0x3E,0x00,0x00,0x00,0x00,0x49,0x45,0x4E,0x44,0xAE,0x42,0x60,0x82]));
  tray = new Tray(nativeImage.createFromPath(iconPath).isEmpty() ? nativeImage.createEmpty() : nativeImage.createFromPath(iconPath));
  tray.setToolTip('HubPro v' + VERSION); tray.setContextMenu(Menu.buildFromTemplate([{ label: 'Открыть HubPro', click: () => { win.show(); win.focus(); } }, { type: 'separator' }, { label: 'Закрыть', click: () => { app.isQuitting = true; app.quit(); } }]));
  tray.on('double-click', () => { win.show(); win.focus(); });
}

function syncPolling(bots, groups) { Object.values(pollingIntervals).forEach(clearInterval); pollingIntervals = {}; botOffsets = {}; bots.forEach(bot => { const token = decrypt(bot.token); botOffsets[bot.id] = 0; const poll = async () => { try { const c = new AbortController(); const t = setTimeout(() => c.abort(), 10000); const data = await (await fetch(`https://api.telegram.org/bot${token}/getUpdates?offset=${botOffsets[bot.id]}&timeout=10`, { signal: c.signal })).json(); clearTimeout(t); if (data.ok && data.result) data.result.forEach(u => { botOffsets[bot.id] = u.update_id + 1; if (u.message?.message?.text) { const g = groups.find(g => g.bot_id === bot.id && g.chat_id === u.message.chat.id.toString()); if (g) { db.prepare('INSERT INTO messages (group_id, text, sent, sender) VALUES (?, ?, 0, ?)').run(g.id, u.message.text, u.message.from.first_name || u.message.from.username); win.webContents.send('tg:incoming', { groupId: g.id, text: u.message.text, time: u.message.date * 1000, sender: u.message.from.first_name || u.message.from.username }); } } }); } catch (e) { if (e.name !== 'AbortError') console.log('Poll', bot.id, e.message); } }; pollingIntervals[bot.id] = setInterval(poll, 3000); }); }

function startScheduleChecker() { scheduleIntervals.forEach(id => clearInterval(id)); scheduleIntervals = []; const id = setInterval(async () => { try { const now = new Date(), ct = now.toTimeString().slice(0, 5), cd = now.toISOString().split('T')[0]; for (const s of db.prepare("SELECT * FROM schedules WHERE status = 'active'").all()) { if (checkScheduleTime(s, ct, cd, now)) await executeSchedule(s); } } catch (e) { console.error(e); } }, 1000); scheduleIntervals.push(id); }
function checkScheduleTime(s, ct, cd, now) { if (ct !== s.scheduled_time.slice(0, 5)) return false; if (s.repeat_type === 'once') return s.scheduled_time.startsWith(cd); const le = s.last_executed ? new Date(s.last_executed) : null; switch (s.repeat_type) { case 'daily': return !le || le.toDateString() !== now.toDateString(); case 'weekly': return !le || Math.floor((now - le) / 86400000) >= 7; case 'monthly': return !le || le.getMonth() !== now.getMonth(); default: return false; } }
async function executeSchedule(s) { try { const bot = db.prepare('SELECT * FROM bots WHERE id = ?').get(s.bot_id); const group = db.prepare('SELECT * FROM groups WHERE id = ?').get(s.group_id); if (!bot || !group) return; const res = await (await fetch(`https://api.telegram.org/bot${decrypt(bot.token)}/sendMessage`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ chat_id: group.chat_id, text: s.text, parse_mode: 'HTML' }) })).json(); if (res.ok) { db.prepare('INSERT INTO schedule_logs (schedule_id, status, error) VALUES (?, ?, ?)').run(s.id, 'success', null); db.prepare('INSERT INTO messages (group_id, text, sent, sender) VALUES (?, ?, 1, ?)').run(group.id, s.text, 'HubPro (авто)'); db.prepare('UPDATE schedules SET last_executed = ? WHERE id = ?').run(new Date().toISOString(), s.id); win.webContents.send('tg:scheduleExecuted', { scheduleId: s.id, success: true }); } else { db.prepare('INSERT INTO schedule_logs (schedule_id, status, error) VALUES (?, ?, ?)').run(s.id, 'error', res.description); win.webContents.send('tg:scheduleExecuted', { scheduleId: s.id, success: false, error: res.description }); } } catch (e) { db.prepare('INSERT INTO schedule_logs (schedule_id, status, error) VALUES (?, ?, ?)').run(s.id, 'error', e.message); win.webContents.send('tg:scheduleExecuted', { scheduleId: s.id, success: false, error: e.message }); } }

function setupAutoUpdater() { autoUpdater.on('update-available', (i) => { if (win?.webContents) win.webContents.send('update-available', i); }); autoUpdater.on('update-downloaded', (i) => { if (win?.webContents) win.webContents.send('update-downloaded', i); dialog.showMessageBox(win, { type: 'info', title: 'Обновление', message: `Загружена версия ${i.version}. Перезапустить?`, buttons: ['Да', 'Нет'] }).then(r => { if (r.response === 0) autoUpdater.quitAndInstall(); }); }); autoUpdater.on('error', e => console.error(e)); if (app.isPackaged) autoUpdater.checkForUpdatesAndNotify(); }
app.on('window-all-closed', () => process.platform !== 'darwin' && app.quit()); app.on('activate', () => BrowserWindow.getAllWindows().length === 0 && createWindow()); app.on('before-quit', () => { scheduleIntervals.forEach(id => clearInterval(id)); if (db) db.close(); });